- backport.sh
- test/acceptance.test.ts
- test/setup.sh
Overrides the committer author/email via environment variables instead of by using configuration options.
> Fixes setting committer author/email

- .github/workflows/backport.yml
- README.md
The pull_request [closed] event contains both merged and unmerged pull
requests. Since the bot now allows to trigger on comment, it has a build
in warning against being triggered for a unmerged pull request, but this
warning is also given when just closing a pull request.
This fixes this by further restricting when to trigger the action.
fixes #32
> Only run on merged pull requests

- .github/workflows/backport.yml
- README.md
GitHub recommends to set the GITHUB_TOKEN permissions to read-only by default. At the same time, our examples did not yet make it clear what permissions are required by this action.
We can simply add the permissions to the examples. This should make it clear what permissions are required, as well as resolve problems for users/repos with read-only defaults.
closes #189
> Permissions in examples

- README.md
The backport-action bot added comments to PRs contain "/backport". This could result in the backport workflow being triggered again, causing an infinite loop of backport messages. By checking the user id of the comment we can prevent comments from backport-action triggering the workflow.
> Workflow should not trigger on own comments

- test/setup.sh
I was unable to run the acceptance tests anymore, after changing my global git config to use `main` as the default initial branch (`init.defaultbranch=main`).
Other users might also have specified a different branch.
We can solve this by being specific about the initial branch name
> Support non-default `init.defaultbranch` git config

- README.md
- action.yml
The inputs `github_token` and `github_workspace` have historically been required. However, we can provide defaults for them using variable expansion for their definition in `action.yml`.
> Default token and workspace

- action.yml
As we're now moving to v1, we can break backward compatibility once. It's a good opportunity to remove the deprecated `version` input. Which hasn't been in use for over a year.
> Remove deprecated version input

- action.yml
The name `backport-action` was already in use. Let's see if `Backport` would be allowed.
We need to merge this to `main` for it to be considered in the publishing (even a tag is not enough).
> Rename action for marketplace

- README.md
To help users easily find the available outputs, they are now documented in the README.
closes #319
> docs: describe outputs

- .github/workflows/release.yml
This workflow can be used to release new versions of the backport-action automatically.
- It sets the version in the package.json, and tags this commit.
- It also creates (or moves) tags for the major and minor version.
- It can also dry-run, meaning it does not push any commits or tags. The created commits are always logged.
resolves #313
> Add automatic release workflow

- .github/workflows/release-next-preview.yml
- .github/workflows/release.yml
This workflow runs on every commit to main and moves the next preview along. In the future, we could also run it on the branches of previously released major versions.
The workflow is automatically updated on new releases so we don't forgot to update the major part of the version (v1.next-preview, v2.next-preview).
> Add release next preview workflow

- .github/workflows/ci.yml
This changes the `CI` workflow to package and publish the artifacts automatically.
By packaging and publishing the artifacts in a workflow, we avoid that they have to be part of a pull request. This allows us to eat our own dogfood and backport pull requests automatically. Previously, pull requests could not be backported because the commit with the artifacts would almost certainly lead to conflicts during cherry-picking.
This pull request also limits when the CI workflow is run. It used to be run both on any `push`, and on any `pull_request` event, which is excessive. The workflow actually only needs to be run on pull requests and on any push to `main` or release branch (`release*`). Additionally, contributors should not be able to change the CI that is run on their changes, so it should …
> Publish artifacts in workflow

- README.md
- action.yml
- src/backport.ts
- src/github.ts
- src/test/backport.test.ts
This pull request enables users to select target branches more leniently.
When the action is triggered for a pull request, its headref should not be selected as target branch because it already contains the commits. There is no use case to cherry-pick the changes to that same branch again. However, it was possible to select the headref both through labels matching the `labels_pattern` input, as well as through the `target_branches` input. This pull request excludes the headref from any of the selected target branches automatically.
One example where this could be useful was highlighted in #343. While glob patterns are not supported in the target_branches input yet, it is possible to expand a glob pattern in a separate step, like:
```yml
- id: branches
shell: bash
run: |
branches=$(git …
```
> Exclude headref from selected branches

- .github/workflows/ci.yml
The CI was supposed to publish artifacts on the main branch and on release branches. However, I misread the documentation for the `contains(search, item)` expression. I expected that search is the value to search for, while item is the thing to search in. It is actually the other way around: search is the thing to search in, and item is what is searched for.
In addition, contains might not be explicit enough. So for safeguarding it may be better to use `startsWith(searchString, searchValue)`. This function 'Returns true when searchString starts with searchValue'.
This problem should now be resolved.
We also need to backport this to v1.3 where the problem also exists. Before that release, there was no automated packaging and publishing of artifacts yet, so there is no need to backport it …
> Publish artifacts on release branches

- .github/workflows/ci.yml
pull_request_target is run in the context of the pull request's base, which makes sense because secrets are made available. But, it meant that the checked out code that was tested was also just that from the base, and not that of the pull request.
To avoid this, I could checkout the code from the pull request's head, but that is dangerous as it may expose secrets to malicious actors.
Instead, its better to just revert to running on pull_request instead.
> ci: run on pull_request

- .github/workflows/ci.yml
This is necessary to not skip the last steps when the pull request is actually merged.
> ci: run ci workflow on pr closed

- .github/workflows/ci.yml
So after all the recent changes, I forgot to adjust the references used to decide whether the artifacts are published and whether the release-next tag is moved.
These refs should be those of the pull_request base (like main and release). Additionally, I just realized that I only have to check these for the move next preview tag step. The artifacts can always be build when the pull request is merged.
However, this made me realize that the artifacts should be published by commit (and pushing) to the pull request's base ref as well. Not to the pull request's head.
> ci: publish artifacts after merging

- .github/workflows/ci.yml
The ref in the event payload (pull_request.base.ref) doesn't have the same prefix of the ref like github.ref does. Let's remove this.
> ci: remove ref prefix

- src/backport.ts
- src/git.ts
- src/main.ts
- src/test/backport.test.ts
- src/test/git.test.ts
Refactors parts of the code to make it easier to write tests, and adds several simple test cases for the git module.
This is part of an attempt to improve the testability of this project.
> Test git module

- README.md
- action.yml
- src/backport.ts
- src/git.ts
- src/main.ts
- src/test/git.test.ts
Adds a new input `merge_commits` that specifies how the action should deal with merge commits on the merged pull request. It supports two settings:
- `fail` fails the backport (default)
- `skip` excludes the merge commits from the commits to cherry-pick
closes #373
> Skip merge commits

- README.md
- action.yml
- src/backport.ts
- src/git.ts
- src/main.ts
- src/test/git.test.ts
Reverts korthout/backport-action#376
> Re-add "Skip merge commits""

- .github/workflows/ci.yml
- .github/workflows/release.yml
- action.yml
- package-lock.json
- package.json
This is needed because node16 is end-of-life. 
See: https://github.com/nodejs/release#release-schedule
See: https://nodejs.org/en/blog/announcements/nodejs16-eol
Since this drops support for node16, it is a breaking change and requires us to move to `v2`.
> Update from node16 to node20

- README.md
- action.yml
- src/backport.ts
- src/github.ts
- src/main.ts
@korthout This patch intends to add three new config options:
1. `copy_milestone`
Copies the milestone from the original PR to all its backport PRs.
2. `copy_reviewers`
Assigns the same reviewers to the backport PRs as were on the original PR.
3. `copy_assignees`  
Assigns the same individuals to the backport PRs as were assigned to the original PR.
All of these options are disabled by default.
Addresses: https://github.com/korthout/backport-action/issues/2
> feat: add support for milestone, assignees and reviewers

- src/backport.ts
This makes several small improvements to the local cherry-picking suggestions:
- No longer suggest `git merge-base` to determine the commits to cherry-pick
- No longer suggest a commit range for cherry-picking but rather be explicit about the commits
- Exclude any skipped merge commits from the commits to cherry-pick
- Use `git switch --create` rather than `git checkout --branch` as it may be easier to understand
Resolves #395 
> **Note**
> I'm making the assumption that all users of backport-action are at least on Git version 2.23 (16 Aug 2019). If anyone prefers the `git checkout --branch` command, please let me know, so I can prioritize #305
> Skip merge commits in suggestion

- .github/workflows/backport.yml
- README.md
the `contains`  expression can lead to unexpected action boot-loops when the error itself contains `/backport`. 
This can be the case when a branch is includes the name "backport" like in this example comment 
```
example error message .. in branch origin/backport-form-xx-to-xx
```
Using `startsWith` to reduce the likeliness of this issue. https://docs.github.com/en/actions/learn-github-actions/expressions#startswith
> fix: change condition to start a backport by comment

- README.md
Apparently, the usage examples previously used the `pull_request` event type, and the extended example was not fully updated.
> docs: fix PR event type in usage example

- README.md
- action.yml
- src/backport.ts
- src/git.ts
- src/github.ts
- src/main.ts
@korthout Github allows multiple merge methods. 
- "Rebase and Merge"
In cases where the merger used "Rebase and Merge" we can use the commits associated with the PR. (Not the commits that will be applied on the `head `branch once the PR is merged). 
- "Squash and Merge"
When using "Squash and Merge" we should use the single squashed commit that ends up on the `head` to accurately reflect any changes in the commit message and to ensure an accurate history between branches.
This patch tries to implement this behavior by looking at the parent of the `merge_commit_sha` that is populated when the PR is merged. If the parent is also associated to the PR (utilising `octokit.rest.repos.listPullRequestsAssociatedWithCommit` to check this) we can assume that the "rebase and merge" strategy was …
> Detect squash and rebase merge methods

- src/utils.ts
The `pull_description` placeholder was incorrectly specified as `${pull_description` (missing the closing bracket). 
When using `${pull_description}`, the `${pull_description` part would be replaced, and the `}` would stay untouched.
> fix: rendering templates due to missing brackets

- src/backport.ts
When the pull request is created in draft mode because of conflicts, the suggestion did not fetch the branch of the opened draft pull request. This meant that the instructions fail when switching, and the commits are cherry-picked on the wrong branch.
Instead, we can fetch the branchname immediately. We no longer need to fetch target either. And while we're at it, we can also simply checkout the branch immediately, so we don't have to switch to it separately.
closes #421
> Suggest to fetch and checkout draft pr branch directly

- src/backport.ts
When resolving the conflicts of a draft backport pull request, the instructions say to checkout the target branch in a new worktree. However, that doesn't make sense for the draft pull request, because we've already created a backport branch. We should checkout the backport branch (branchname) instead of target.
resolves #421
> Checkout draft branch instead of target in suggestion

- README.md
- action.yml
- src/main.ts
It should be possible to add labels that contain spaces. So we need to find another delimiter. GitHub does not seem to support labels that include commas, so we can use this instead.
> Delimit `add_labels` using comma

- package-lock.json
- package.json
By being explicit about the version numbers, we are more clear about how we expect to build this project.
Note that here we were already using dedent 1.7.0 (in package-lock) but were defining it as ^1.6.0 in package.json.
> Define dependency versions explicitly
